version: '3.4'

services:
  fc.pixelflix.catalog.db:
    container_name: catalog-db
    hostname: catalog-db
    image: mysql
    ports:
      - 3307:3307
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3307

networks:
  default:
    name: service_catalog
